version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: math-formulas-dataset-builder-app
    restart: unless-stopped
    volumes:
      - /opt/docs:/app/docs:ro
    working_dir: /app
    tty: true
    stdin_open: true
    command: python main.py